/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserChallengeStatus = IDL.Record({
  'hasActiveChallenge' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChallenge' : IDL.Func([Time], [IDL.Nat], []),
  'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
  'deleteRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'generateInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getActiveChallengeIdForCreator' : IDL.Func(
      [],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getActiveChallengeIdForParticipant' : IDL.Func(
      [],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getAllChallengeParticipantProfiles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
      ['query'],
    ),
  'getAssignmentRecordings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(ExternalBlob)))],
      ['query'],
    ),
  'getAvailableInvitationCodes' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeAudioRecordings' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getChallengeParticipants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getChallengeStartTime' : IDL.Func([IDL.Nat], [Time], ['query']),
  'getParticipantRecording' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
      [ExternalBlob],
      ['query'],
    ),
  'getRecording' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [ExternalBlob],
      ['query'],
    ),
  'getUserChallengeStatus' : IDL.Func([], [UserChallengeStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveChallenge' : IDL.Func([IDL.Nat], [], []),
  'redeemInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRecording' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'updateStartTime' : IDL.Func([IDL.Nat, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserChallengeStatus = IDL.Record({ 'hasActiveChallenge' : IDL.Bool });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChallenge' : IDL.Func([Time], [IDL.Nat], []),
    'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
    'deleteRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'generateInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getActiveChallengeIdForCreator' : IDL.Func(
        [],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getActiveChallengeIdForParticipant' : IDL.Func(
        [],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getAllChallengeParticipantProfiles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
        ['query'],
      ),
    'getAssignmentRecordings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(ExternalBlob)))],
        ['query'],
      ),
    'getAvailableInvitationCodes' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeAudioRecordings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getChallengeParticipants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getChallengeStartTime' : IDL.Func([IDL.Nat], [Time], ['query']),
    'getParticipantRecording' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
        [ExternalBlob],
        ['query'],
      ),
    'getRecording' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [ExternalBlob],
        ['query'],
      ),
    'getUserChallengeStatus' : IDL.Func([], [UserChallengeStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveChallenge' : IDL.Func([IDL.Nat], [], []),
    'redeemInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRecording' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'updateStartTime' : IDL.Func([IDL.Nat, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };