/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Recording = IDL.Record({
  'value' : ExternalBlob,
  'isShared' : IDL.Bool,
});
export const BuildInfo = IDL.Record({
  'stableDeployTime' : IDL.Opt(IDL.Int),
  'deployTime' : IDL.Nat,
  'version' : IDL.Text,
  'buildTime' : IDL.Nat,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'isEdited' : IDL.Bool,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'replyTo' : IDL.Opt(IDL.Nat),
});
export const UserChallengeStatus = IDL.Record({
  'hasActiveChallenge' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChallenge' : IDL.Func([Time], [IDL.Nat], []),
  'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
  'deleteRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'editMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'generateInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActiveChallengeIdForCreator' : IDL.Func(
      [],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getActiveChallengeIdForParticipant' : IDL.Func(
      [],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getAllChallengeParticipantProfiles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
      ['query'],
    ),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAssignmentRecordings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Recording)))],
      ['query'],
    ),
  'getAvailableInvitationCodes' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getBuildInfo' : IDL.Func([], [BuildInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeAudioRecordings' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getChallengeParticipants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getChallengeStartTime' : IDL.Func([IDL.Nat], [Time], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMessage' : IDL.Func([IDL.Nat, IDL.Nat], [ChatMessage], ['query']),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getParticipantRecording' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
      [ExternalBlob],
      ['query'],
    ),
  'getRecording' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [ExternalBlob],
      ['query'],
    ),
  'getUserChallengeStatus' : IDL.Func([], [UserChallengeStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveChallenge' : IDL.Func([IDL.Nat], [], []),
  'postMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'redeemInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRecording' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'shareRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateStartTime' : IDL.Func([IDL.Nat, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Recording = IDL.Record({
    'value' : ExternalBlob,
    'isShared' : IDL.Bool,
  });
  const BuildInfo = IDL.Record({
    'stableDeployTime' : IDL.Opt(IDL.Int),
    'deployTime' : IDL.Nat,
    'version' : IDL.Text,
    'buildTime' : IDL.Nat,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'isEdited' : IDL.Bool,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'replyTo' : IDL.Opt(IDL.Nat),
  });
  const UserChallengeStatus = IDL.Record({ 'hasActiveChallenge' : IDL.Bool });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChallenge' : IDL.Func([Time], [IDL.Nat], []),
    'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
    'deleteRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'editMessage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'generateInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActiveChallengeIdForCreator' : IDL.Func(
        [],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getActiveChallengeIdForParticipant' : IDL.Func(
        [],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getAllChallengeParticipantProfiles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAssignmentRecordings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(Recording)))],
        ['query'],
      ),
    'getAvailableInvitationCodes' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getBuildInfo' : IDL.Func([], [BuildInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeAudioRecordings' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getChallengeParticipants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getChallengeStartTime' : IDL.Func([IDL.Nat], [Time], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMessage' : IDL.Func([IDL.Nat, IDL.Nat], [ChatMessage], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getParticipantRecording' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Nat, IDL.Text],
        [ExternalBlob],
        ['query'],
      ),
    'getRecording' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [ExternalBlob],
        ['query'],
      ),
    'getUserChallengeStatus' : IDL.Func([], [UserChallengeStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveChallenge' : IDL.Func([IDL.Nat], [], []),
    'postMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'redeemInvitationCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeParticipant' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRecording' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'shareRecording' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateStartTime' : IDL.Func([IDL.Nat, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };