/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BuildInfo {
  'stableDeployTime' : [] | [bigint],
  'deployTime' : bigint,
  'version' : string,
  'buildTime' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'text' : string,
  'sender' : Principal,
  'isEdited' : boolean,
  'timestamp' : bigint,
  'senderName' : string,
  'replyTo' : [] | [bigint],
}
export type ExternalBlob = Uint8Array;
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Recording { 'value' : ExternalBlob, 'isShared' : boolean }
export type Time = bigint;
export interface UserChallengeStatus { 'hasActiveChallenge' : boolean }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChallenge' : ActorMethod<[Time], bigint>,
  'deleteChallenge' : ActorMethod<[bigint], undefined>,
  'deleteRecording' : ActorMethod<[bigint, bigint, string], undefined>,
  'editMessage' : ActorMethod<[bigint, bigint, string], undefined>,
  'generateInvitationCode' : ActorMethod<[bigint, string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActiveChallengeIdForCreator' : ActorMethod<[], [] | [bigint]>,
  'getActiveChallengeIdForParticipant' : ActorMethod<[], [] | [bigint]>,
  'getAllChallengeParticipantProfiles' : ActorMethod<
    [bigint],
    Array<[Principal, [] | [UserProfile]]>
  >,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAssignmentRecordings' : ActorMethod<
    [bigint, bigint, string],
    Array<[Principal, [] | [Recording]]>
  >,
  'getAvailableInvitationCodes' : ActorMethod<[bigint], Array<string>>,
  'getBuildInfo' : ActorMethod<[], BuildInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallengeAudioRecordings' : ActorMethod<[bigint], Array<Principal>>,
  'getChallengeParticipants' : ActorMethod<[bigint], Array<Principal>>,
  'getChallengeStartTime' : ActorMethod<[bigint], Time>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMessage' : ActorMethod<[bigint, bigint], ChatMessage>,
  'getMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getParticipantRecording' : ActorMethod<
    [bigint, Principal, bigint, string],
    ExternalBlob
  >,
  'getRecording' : ActorMethod<[bigint, bigint, string], ExternalBlob>,
  'getUserChallengeStatus' : ActorMethod<[], UserChallengeStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveChallenge' : ActorMethod<[bigint], undefined>,
  'postMessage' : ActorMethod<[bigint, string, [] | [bigint]], bigint>,
  'redeemInvitationCode' : ActorMethod<[bigint, string], undefined>,
  'removeParticipant' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRecording' : ActorMethod<
    [bigint, bigint, string, ExternalBlob],
    undefined
  >,
  'shareRecording' : ActorMethod<[bigint, bigint, string, boolean], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateStartTime' : ActorMethod<[bigint, Time], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];